name: teresarivera
favicon: null
layout_spectrum: 0.3942225573118776
typography_spectrum: 0.6359452593605965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0911'
    - '#e0e9ec'
    - '#d1a672'
    - '#8e81ac'
    - '#335fc0'
  brandStrength: 0.11659265006892383
  lightness: 0.33606769726611674
  saturation: 0.1861418962944299
  rhythmicContrast: 0.9570178384892642
purpose: []
